version: "3"


services:
  api:
    build:
      context: .
    command:
      - "python -m uvicorn --host 0.0.0.0 --port 8000 app.main:app"
    ports:
      - "8000-8100:8000"
    env_file:
      - .env
    volumes:
      - db-data:/var/api/db-files
#     somehow here a dynamic mapping is needed due to the fact that sqlite file location can be configured via env
volumes:
  db-data: